### ISSUE TITLE
Radio 1 renamed to TOPP40

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-nordic-logos#10]
Radio 1 renamed to TOPP40

https://www.telenorsat.com/broadcast-services/implemented_broadcast_changes/

https://listenapi.s3.amazonaws.com/img/ConfigWebHeaderLogoSVGImageUrl/170.svg?ver=1504696854

**Comment by Jasmeet181** [comment]
Thanks Dalmore.

**Comment by dalmore72** [comment]
Thanks
