### ISSUE TITLE
Auto Motor og Sport TV

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-nordic-logos#12]
Auto Motor og Sport TV Change name.

Bilkanalen Auto Motor og Sport TV

[Auto Motor og Sport TV.zip](https://github.com/Jasmeet181/mediaportal-nordic-logos/files/4299510/Auto.Motor.og.Sport.TV.zip)

**Comment by Jasmeet181** [comment]
Thanks again Dalmore.

**Comment by dalmore72** [comment]
Thanks
