### ISSUE TITLE
New logos

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-nordic-logos#2]
New logos Ruv Island and Disney Junior

http://www.ruv.is/ruv-okkar-allra/auglysingar

[Nordic.zip](https://github.com/Jasmeet181/mediaportal-nordic-logos/files/2904903/Nordic.zip)

**Comment by Jasmeet181** [comment]
Thanks Dalmore. I've had the Disney Junior logo for a few days but haven't found the HD logo, have you? Based on the [+1 logo](http://guidatv.sky.it/app/guidatv/images/epgimages/channels/home/132_home.png), I've guessed that the layout is like [this old one](https://images.radiotimes.com/remote/images.atlas.metabroadcast.com/pressassociation.com/channels/p2201305151793.png?quality=60&mode=fit&404=tv).

**Comment by dalmore72** [comment]
Sorry has not found it yet but continues to search :)
