### ISSUE TITLE
Telia Liiga

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-nordic-logos#4]
Telia Liiga 1 and 2 Changed to HD

https://www.canaldigital.fi/tv-kanavat/?channel=telia-liiga-1-hd

https://www.canaldigital.fi/tv-kanavat/?channel=telia-liiga-2-hd

**Comment by dalmore72** [comment]
There is also a new logo Tronder TV

This is the best logo I've found so far

![Tronder TV](https://user-images.githubusercontent.com/16014375/55426532-52392980-5585-11e9-900e-5050b601592f.png)

**Comment by Jasmeet181** [comment]
Thanks Dalmore, I'm guessing that the Telia Liiga HD logos are supposed to be purple like the rest, if that's wrong let me know. There's a slightly higher quality Tronder TV logo at https://tindved.no/bedrifter/tronder-tv/

**Comment by dalmore72** [comment]
Thank you purple is correct 👍 


![thumbs-up](https://user-images.githubusercontent.com/16014375/55474042-7b52cc00-5610-11e9-953f-4dbcacbccfb9.png)
