### ISSUE TITLE
New logo Tlc

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-nordic-logos#6]
New logo TLC

[TLC.zip](https://github.com/Jasmeet181/mediaportal-nordic-logos/files/3067978/TLC.zip)

New Channel Telia Liiga UHD 

https://www.canaldigital.fi/tv-kanavat/?channel=telia-liiga-uhd

https://www.telenorsat.com/broadcast-services/implemented_changes/

**Comment by Jasmeet181** [comment]
Thanks Dalmore, I think that all European versions have switched.

**Comment by dalmore72** [comment]
Thanks
