### ISSUE TITLE
 DanToto renamed to Sport Live

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-nordic-logos#8]
DanToto renamed to Sport Live

https://www.telenorsat.com/broadcast-services/implemented_broadcast_changes/

https://www.sport-live.dk/

![sport live](https://user-images.githubusercontent.com/16014375/62567645-e7c62c00-b88b-11e9-9639-04bf5af6d096.png)

**Comment by Jasmeet181** [comment]
Thanks Dalmore.

**Comment by dalmore72** [comment]
Thanks, but I forgot to include the changes to mtv3 finland

https://manualer.bonnierbroadcasting.se/d/0EMuYcAL2hlO/mtv-style-guide#/mtv3-1565067696

**Comment by dalmore72** [comment]
Thanks 👍
